export const quote = {
  customer: {
    name: "Matron Lelah",
    address: "Persiaran Kayangan, Seksyen 7, 40000b Shah Alam, Selangor",
    department: "O&G",
  },
  items: [
    {
      no: 1,
      productCode: "CD3-6B",
      desc: 'GENESIS Sterilization Full-Length container, perforated bottom, hard-coated anodized aluminium, with 2 ID tags, 23" x 12" x 6" (58.4cm x 30.5cm x 15.2cm). ',
      qty: 1,
      oum: "pc",
      price: 2970,
    },
    {
      no: 2,
      productCode: "BP3-3A",
      desc: 'GENESIS Full-Length Basket, perforated, standard handles, 20 1/2" x 10 1/2" x 3" (52cm x 26.7cm x 7.6cm).',
      qty: 1,
      oum: "pc",
      price: 998.0,
    },
    {
      no: 3,
      productCode: "18-0099",
      desc: "Heparin Flushing Needle, 2.0mm diameter, s/steel, 45mm",
      qty: 1,
      oum: "pc",
      price: 284.0,
    },
    {
      no: 4,
      productCode: "40-1018A1",
      desc: 'Kerrison Laminectomy Punch, 1mm bite, 90° up, regular footplate, s/steel, working length 180mm, 7"',
      qty: 1,
      oum: "pc",
      price: 4389,
    },
    {
      no: 5,
      productCode: "40-1018A1",
      desc: 'Structurae™ Bayonet Micro-Needle Holder, ultra-lightweight, straight, round shell handles with perforations, s/steel, 220mm, 8 3/4"',
      qty: 1,
      oum: "pc",
      price: 5211,
    },
    {
      no: 6,
      productCode: "40-1018",
      desc: 'LINVASIVE™ Micro Needle holder, 0.5mm tip, straight, rotable shaft with flushing channel, bayonet shape, working length 120mm, s/steel, 260mm, 10 1/2"',
      qty: 1,
      oum: "pc",
      price: 9875,
    },
    {
      no: 7,
      productCode: "41-4400",
      desc: 'LINVASIVE™ Micro Needle holder, 0.5mm tip, straight, rotable shaft with flushing channel, bayonet shape, working length 120mm, s/steel, 260mm, 10 1/2"',
      qty: 1,
      oum: "pc",
      price: 9875,
    },
    {
      no: 8,
      productCode: "53.30.00",
      desc: "Episiotomy set in canvas roll, stored in metal case 200x100x30mm, consisting of:- 1x dressing forceps, 1x tissue forceps,1x Mathieu needle holder, 1x Braun-Stadler episiotomy scissors, 1x tissue scissors, 1x Kocher hemostatic forceps, 1x needle case",
      qty: 1,
      oum: "pc",
      price: 2198,
    },
  ],
};
